### ISSUE TITLE
Dead code in db.py load ?

### ISSUE THREAD

**Issue by Annakan** [emory-libraries/eulexistdb#12]
this code from   db.py line 444 has a syntax error :
The overwrite parameter has been suppressed from the signature but not from the final test 
**(overwrite and response.status_code == requests.codes.ok)**

```python
        def load(self, xml, path):
        """Insert or overwrite a document in the database.

        :param xml: string or file object with the document contents
        :param path: destination location in the database
        :rtype: boolean indicating success

        """
        if hasattr(xml, 'read'):
            xml = xml.read()

        logger.debug('load %s', path)
        # NOTE: overwrite is assumed by REST
        response = self.session.put(self.restapi_path(path), xml, stream=False,
                                    **self.session_opts)
        if response.status_code == requests.codes.bad_request:
            # response is HTML, not xml...
            # could use regex or beautifulsoup to pull out the error
            raise ExistDBException

        # expect 201 created for new documents, 200 for
        # successful update of an existing document
        return response.status_code == requests.codes.created or \
            (overwrite and response.status_code == requests.codes.ok)
```

This code has been pulled from eulexistdb-0.21.0 from pypi.
You probably have a phantom test  too since this code can't possibly work.

**Comment by rlskoeser** [comment]
Drat, thanks for catching that.  The overwrite parameter was dropped since the behavior had changed, and I obviously missed something.  I wonder how I didn't catch that in the tests?

I'll try to get a hotfix out soon.

**Comment by rlskoeser** [comment]
In testing my eXist instance it looks like I'm getting a 201 response every time, even when I update the same document - which explains why it wasn't a problem for me, because it never got to the other code.  Does your exist behave differently?

Also, it appears I wasn't testing the load method directly, even though it's used extensively in the test code to test other functionality. Fixing that now...
