### ISSUE TITLE
reraise exception in `ExistDB.create_account`

### ISSUE THREAD

**Issue by lddubeau** [emory-libraries/eulexistdb#2]
The `create_account` method is currently [defined](https://github.com/emory-libraries/eulexistdb/blob/e097578c7f8d0b3247ea28ad3bd895fa505094a5/eulexistdb/db.py#L689) as:

```
    def create_account(self, username, password, groups):
        try:
            result = self.query('sm:create-account("%s", "%s", "%s")' % \
                (username, password, groups))
            return True
        except ExistDBException as err:
            if 'user account with username %s already exists' % username in err.message():
                return False
            # NOTE: might be possible to also get a group error here
            # perhaps just check for 'already exists' ?
```

At the very least, the exception handler should reraise `err` if it is not going to return `False`. I ran into a problem where I was mistakenly not properly logged into eXist-db. This function failed silently rather than let the exception propagate up. The exception's message clearly indicated what was the problem and so would have been immensely useful to see. (For the record, I'm no longer using this method. I suspect it is meant to be private and used in testing but for the sake of people writing test code, it should not swallow exceptions.)

**Comment by rlskoeser** [comment]
Thats a good point, thanks for document.  I think currently I only use it to help with the unit testing, but that doesn't mean it shouldn't do the right thing if an error comes up.

**Comment by rlskoeser** [comment]
Closing, fix will be in next release.
