### ISSUE TITLE
xmlrpclib does not support extended types and this may cause XML-RPC calls to fail when unmarshalling return values

### ISSUE THREAD

**Issue by lddubeau** [emory-libraries/eulexistdb#4]
Let me first make clear that the problem is not in `eulexistdb` itself but this is a problem that users of `eulexistdb` may encounter. So I'm posting here so that others who may run into the issue can (hopefully) readily figure out what is going on.

The problem is that eXist returns XML-RPC types that `xmlrpclib` does not support. The issue has been reported on the Python side:

* https://bugs.python.org/issue26873
* https://bugs.python.org/issue26885

And patches have been submitted but it is unclear when a fix will land in released versions of Python.

I encountered the problem while doing XML-RPC calls through the `server` field of `ExistDB` objects. Calling the XML-RPC method `removeGroup`, for instance, will result in this error:

    xmlrpclib.ResponseError: ResponseError("unknown tag u'ex:nil'",)

Since this failure is not an option for me, I inspected the patches submitted in the Python bug reports listed above and created a runtime patch that allows my code to work. I could contribute it to `eulexistdb` if desirable.

(I know about `sm:create-group`, `sm:delete-group`, etc. I decided against using them for now.)

**Comment by rlskoeser** [comment]
Whoa, interesting.  The last time I looked at python xmlrpclib it didn't look very active; I figured that was because xmlrpc isn't used as much anymore.

A pull request with the patch and some brief documentation sounds useful to me.  And it sounds like it should be pretty generate a test case for one of the requests that causes the problem, since you already know an api call that's a problem.

**Comment by lddubeau** [comment]
Ok, I'm busy with things other than eXist-db right at the moment but I should be able to get something together next week.

**Comment by lddubeau** [comment]
Question before I put in a pull request.

Should the patch be performed automatically or need be explicitly requested? Note that in either case, the code I'm submitting will determine whether the patch is needed and *won't* perform it if it is *not* needed. In pseudo-code, it is like this:

        if is_patch_needed():
            perform_patch()

In the implementation I made for my project, I have exactly the logic above *at the top level of a module of mine*. This means that the check is always performed and the patch automatically applied when the check determines that `xmlrpclib` is faulty.

However, thinking about this a bit more, I'm now inclined to put the code above in a call that must be explicitly made. Something like:

        def patch_if_needed():
            if is_patch_needed():
                perform_patch()

So users would have to call `patch_if_needed()` explicitly to benefit from the patch. If there are unintended consequences to the patch, it would be easy to not activate it: just don't call `patch_if_needed`.

**Comment by rlskoeser** [comment]
@lddubeau making it opt-in sounds sensible to me.

**Comment by rlskoeser** [comment]
Added a note with documentation in the top-level db docs.  Fix will be in the next release.
