### ISSUE TITLE
The overwrite parameter on ExistDB.load should be removed.

### ISSUE THREAD

**Issue by lddubeau** [emory-libraries/eulexistdb#9]
For one thing, it is not used for anything else than logging.

But worse than this, its presence is very misleading, because one would expect that having `overwrite=False` (*which is the default*) would prevent overwrites. However, it is not used and as a [comment](https://github.com/emory-libraries/eulexistdb/blob/e097578c7f8d0b3247ea28ad3bd895fa505094a5/eulexistdb/db.py#L376) points out:

```
# NOTE: overwrite is assumed by REST
```

So people who would expect `overwrite=False` to be meaningful are going to have a surprise when they find that data that should not have been overwritten has been overwritten. Luckily, I found about the issue in testing. I ran a test that was overwriting some data and was expecting a failure since I had not set `overwrite=True`.

**Comment by rlskoeser** [comment]
Thanks for reporting it.  Must be a holdover from when that method used the xmlrpc api.

**Comment by rlskoeser** [comment]
Closing, fix will be in the next release.
